name: "Deploy CI"

on:
  push:
    branches:
      - "main"

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy application"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setp-node@v1
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
          node-version-file: ".nvmrc"
      - name: "Deploy application"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
          URL: ${{ secrets.URL }}
